version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: nestjs-price-tracker
    ports:
      - '3000:3000' 
    environment:
      - NODE_ENV=production
      - DB_HOST='aws-0-ap-south-1.pooler.supabase.com'
      - DB_PORT=6543
      - DB_USERNAME='postgres.fumkqloqwkgpmfecusci'
      - DB_PASSWORD='Pulkit@123#'
      - DB_DATABASE=postgres
      - MAIL_HOST='smtp.gmail.com'
      - MAIL_PORT=587
      - MAIL_USER='thereciprocalolutions.projects@gmail.com'
      - MAIL_PASS='cgenxthsgpwplxoy'
      - MORALIS_API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjI4YWFiYTQ0LTllODctNDA2NS1hODRiLWZhMTc0NTM3MzBhYiIsIm9yZ0lkIjoiNDEwMzU4IiwidXNlcklkIjoiNDIxNzA3IiwidHlwZUlkIjoiMTZjMTQ4NDgtNzQ0Ny00N2FkLTk3OTYtOTJiZjM1ZWIwZmM0IiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3Mjc5NzcwNDUsImV4cCI6NDg4MzczNzA0NX0.Jk62MZ_M6rpYY8SHXYpDVytu3R9mr4LJKtjSHk_ebfQ'
    depends_on:
      - db 
    networks:
      - nestjs_network

  db:
    image: postgres:14-alpine 
    container_name: nestjs-database
    environment:
      POSTGRES_DB: 'aws-0-ap-south-1.pooler.supabase.com'
      POSTGRES_USER: 'postgres.fumkqloqwkgpmfecusci'
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '6543:6543'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge

volumes:
  db_data:
